### PR TITLE
add google creds to both containers and initContainers

### PR DESCRIPTION
**Pull request by akakakakakaa**
Hi, I want to use google credentials to initcontainer also. 

I think there is common use case that run a container after downloading metadata from initcontainer.

### CODE REVIEW

**Comment by sharifelgamal** [comment]
Hey @akakakakakaa, this seems like a reasonable change. If you sign the CLA, I can test and merge it.

**Comment by akakakakakaa** [comment]
Thank you for your response. I changed commit to CLA verified email.

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
